import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import * as i0 from "@angular/core";
export class About {
    static ɵfac = function About_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || About)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: About, selectors: [["app-about"]], decls: 89, vars: 0, consts: [[1, "section", 2, "border-bottom", "none"], [1, "container", "about-grid"], [1, "eyebrow"], [1, "timeline"], [1, "tl-item"], [1, "tl-period"], [1, "tl-content"], [1, "tl-org"], [1, "tl-desc"], [1, "seeking-box"], ["routerLink", "/contact", 1, "btn", "btn-primary", 2, "margin-top", "20px", "width", "100%", "justify-content", "center"]], template: function About_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵelementStart(0, "section", 0)(1, "div", 1)(2, "div")(3, "span", 2);
            i0.ɵɵtext(4, "\u00C0 propos");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(5, "h1");
            i0.ɵɵtext(6, "D'un poste de support \u00E0 la conception d'interfaces");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(7, "p");
            i0.ɵɵtext(8, " Avant de d\u00E9velopper, j'ai pass\u00E9 du temps ");
            i0.ɵɵelementStart(9, "strong");
            i0.ɵɵtext(10, "sur le terrain et au support");
            i0.ɵɵelementEnd();
            i0.ɵɵtext(11, " \u2014 \u00E0 diagnostiquer des pannes, configurer des postes, accompagner des utilisateurs. Cette exp\u00E9rience m'a appris \u00E0 comprendre un probl\u00E8me avant d'y r\u00E9pondre. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(12, "p");
            i0.ɵɵtext(13, " Aujourd'hui, je d\u00E9veloppe avec ");
            i0.ɵɵelementStart(14, "strong");
            i0.ɵɵtext(15, "Angular");
            i0.ɵɵelementEnd();
            i0.ɵɵtext(16, " dans le cadre de la premi\u00E8re cohorte de l'");
            i0.ɵɵelementStart(17, "strong");
            i0.ɵɵtext(18, "Angular Talent Lab 2026");
            i0.ɵɵelementEnd();
            i0.ɵɵtext(19, " \u00E0 l'Orange Digital Center Cameroun, o\u00F9 je construis des applications compl\u00E8tes : composants, services, routing, formulaires, consommation d'API. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(20, "p");
            i0.ɵɵtext(21, " Je cherche \u00E0 transformer ce double bagage \u2014 technique et terrain \u2014 en une contribution utile au sein d'une \u00E9quipe produit. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(22, "h2");
            i0.ɵɵtext(23, "Parcours");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(24, "div", 3)(25, "div", 4)(26, "div", 5);
            i0.ɵɵtext(27, "2026");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(28, "div", 6)(29, "h3");
            i0.ɵɵtext(30, "Angular Talent Lab \u2014 1\u00E8re cohorte");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(31, "div", 7);
            i0.ɵɵtext(32, "Orange Digital Center Cameroun");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(33, "p", 8);
            i0.ɵɵtext(34, " Formation intensive Angular moderne : standalone components, signals, RxJS, routing, formulaires r\u00E9actifs. D\u00E9veloppement de plusieurs projets complets. ");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(35, "div", 4)(36, "div", 5);
            i0.ɵɵtext(37, "Juin 2025 \u2014 F\u00E9v. 2026");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(38, "div", 6)(39, "h3");
            i0.ɵɵtext(40, "Charg\u00E9 des Op\u00E9rations / Superviseur Terrain");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(41, "div", 7);
            i0.ɵɵtext(42, "ADG Group \u2014 Projet Accent Media");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(43, "p", 8);
            i0.ɵɵtext(44, "Supervision d'op\u00E9rations terrain, coordination et suivi d'ex\u00E9cution.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(45, "div", 4)(46, "div", 5);
            i0.ɵɵtext(47, "F\u00E9v. \u2014 Mai 2024");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(48, "div", 6)(49, "h3");
            i0.ɵɵtext(50, "T\u00E9l\u00E9conseiller");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(51, "div", 7);
            i0.ɵɵtext(52, "\u2014 organisation \u00E0 pr\u00E9ciser \u2014");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(53, "p", 8);
            i0.ɵɵtext(54, "Relation client, gestion des demandes et des incidents \u00E0 distance.");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(55, "div", 4)(56, "div", 5);
            i0.ɵɵtext(57, "Stage");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(58, "div", 6)(59, "h3");
            i0.ɵɵtext(60, "Stage \u2014 support / environnement IT");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(61, "div", 7);
            i0.ɵɵtext(62, "ENEO Cameroun");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(63, "p", 8);
            i0.ɵɵtext(64, "D\u00E9tails du stage \u00E0 compl\u00E9ter (missions, outils utilis\u00E9s).");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(65, "div", 4)(66, "div", 5);
            i0.ɵɵtext(67, "Stage");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(68, "div", 6)(69, "h3");
            i0.ɵɵtext(70, "Stage \u2014 support / environnement IT");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(71, "div", 7);
            i0.ɵɵtext(72, "SONATREL");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(73, "p", 8);
            i0.ɵɵtext(74, "D\u00E9tails du stage \u00E0 compl\u00E9ter (missions, outils utilis\u00E9s).");
            i0.ɵɵelementEnd()()()()();
            i0.ɵɵelementStart(75, "div", 9)(76, "h3");
            i0.ɵɵtext(77, "Ce que je cherche");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(78, "ul")(79, "li");
            i0.ɵɵtext(80, "Une opportunit\u00E9 junior en d\u00E9veloppement Front-End / Angular");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(81, "li");
            i0.ɵɵtext(82, "Une \u00E9quipe o\u00F9 le code est relu, discut\u00E9, am\u00E9lior\u00E9");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(83, "li");
            i0.ɵɵtext(84, "Un environnement pour progresser rapidement et durablement");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(85, "li");
            i0.ɵɵtext(86, "La possibilit\u00E9 d'apporter aussi une culture support / IT");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(87, "a", 10);
            i0.ɵɵtext(88, "Me contacter");
            i0.ɵɵelementEnd()()()();
        } }, dependencies: [RouterLink], styles: [".about-grid[_ngcontent-%COMP%] { display: grid; grid-template-columns: 1.4fr 1fr; gap: 64px; }\n.about-grid[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] { font-size: clamp(1.9rem, 4vw, 2.5rem); margin-top: 10px; }\n.about-grid[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%]    > p[_ngcontent-%COMP%] { color: var(--%NS%color-text-muted); margin: 16px 0; font-size: 1.02rem; }\n.about-grid[_ngcontent-%COMP%]   strong[_ngcontent-%COMP%] { color: var(--%NS%color-text); font-weight: 500; }\n.about-grid[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] { font-size: 1.3rem; margin-top: 48px; margin-bottom: 24px; }\n\n.seeking-box[_ngcontent-%COMP%] {\n  background: var(--%NS%color-surface); border: 1px solid var(--%NS%color-border);\n  border-left: 2px solid var(--%NS%color-primary); border-radius: 4px;\n  padding: 26px 24px; align-self: start;\n}\n.seeking-box[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size: 1rem; margin-bottom: 14px; }\n.seeking-box[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] { font-size: 0.92rem; color: var(--%NS%color-text-muted); padding: 7px 0; border-top: 1px dashed var(--%NS%color-border); }\n.seeking-box[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:first-child { border-top: none; }\n\n.timeline[_ngcontent-%COMP%] { position: relative; }\n.tl-item[_ngcontent-%COMP%] { display: grid; grid-template-columns: 130px 1fr; gap: 24px; padding: 22px 0; border-top: 1px solid var(--%NS%color-border); }\n.tl-item[_ngcontent-%COMP%]:first-child { border-top: none; padding-top: 0; }\n.tl-period[_ngcontent-%COMP%] { font-family: var(--%NS%font-mono); font-size: 0.76rem; color: var(--%NS%color-text-faint); padding-top: 3px; }\n.tl-content[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] { font-size: 1rem; font-family: var(--%NS%font-body); font-weight: 600; }\n.tl-org[_ngcontent-%COMP%] { font-family: var(--%NS%font-mono); font-size: 0.78rem; color: var(--%NS%color-secondary); margin-top: 3px; }\n.tl-desc[_ngcontent-%COMP%] { color: var(--%NS%color-text-muted); font-size: 0.9rem; margin-top: 8px; }\n\n@media (max-width: 900px) { .about-grid[_ngcontent-%COMP%] { grid-template-columns: 1fr; } }\n@media (max-width: 640px) { .tl-item[_ngcontent-%COMP%] { grid-template-columns: 1fr; gap: 6px; } }"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(About, [{
        type: Component,
        args: [{ selector: 'app-about', standalone: true, imports: [RouterLink], template: "<section class=\"section\" style=\"border-bottom:none;\">\n  <div class=\"container about-grid\">\n    <div>\n      <span class=\"eyebrow\">\u00C0 propos</span>\n      <h1>D'un poste de support \u00E0 la conception d'interfaces</h1>\n      <p>\n        Avant de d\u00E9velopper, j'ai pass\u00E9 du temps <strong>sur le terrain et au support</strong> \u2014\n        \u00E0 diagnostiquer des pannes, configurer des postes, accompagner des utilisateurs.\n        Cette exp\u00E9rience m'a appris \u00E0 comprendre un probl\u00E8me avant d'y r\u00E9pondre.\n      </p>\n      <p>\n        Aujourd'hui, je d\u00E9veloppe avec <strong>Angular</strong> dans le cadre de la premi\u00E8re\n        cohorte de l'<strong>Angular Talent Lab 2026</strong> \u00E0 l'Orange Digital Center Cameroun,\n        o\u00F9 je construis des applications compl\u00E8tes : composants, services, routing,\n        formulaires, consommation d'API.\n      </p>\n      <p>\n        Je cherche \u00E0 transformer ce double bagage \u2014 technique et terrain \u2014 en une\n        contribution utile au sein d'une \u00E9quipe produit.\n      </p>\n\n      <h2>Parcours</h2>\n      <div class=\"timeline\">\n        <div class=\"tl-item\">\n          <div class=\"tl-period\">2026</div>\n          <div class=\"tl-content\">\n            <h3>Angular Talent Lab \u2014 1\u00E8re cohorte</h3>\n            <div class=\"tl-org\">Orange Digital Center Cameroun</div>\n            <p class=\"tl-desc\">\n              Formation intensive Angular moderne : standalone components, signals, RxJS,\n              routing, formulaires r\u00E9actifs. D\u00E9veloppement de plusieurs projets complets.\n            </p>\n          </div>\n        </div>\n        <div class=\"tl-item\">\n          <div class=\"tl-period\">Juin 2025 \u2014 F\u00E9v. 2026</div>\n          <div class=\"tl-content\">\n            <h3>Charg\u00E9 des Op\u00E9rations / Superviseur Terrain</h3>\n            <div class=\"tl-org\">ADG Group \u2014 Projet Accent Media</div>\n            <p class=\"tl-desc\">Supervision d'op\u00E9rations terrain, coordination et suivi d'ex\u00E9cution.</p>\n          </div>\n        </div>\n        <div class=\"tl-item\">\n          <div class=\"tl-period\">F\u00E9v. \u2014 Mai 2024</div>\n          <div class=\"tl-content\">\n            <h3>T\u00E9l\u00E9conseiller</h3>\n            <div class=\"tl-org\">\u2014 organisation \u00E0 pr\u00E9ciser \u2014</div>\n            <p class=\"tl-desc\">Relation client, gestion des demandes et des incidents \u00E0 distance.</p>\n          </div>\n        </div>\n        <div class=\"tl-item\">\n          <div class=\"tl-period\">Stage</div>\n          <div class=\"tl-content\">\n            <h3>Stage \u2014 support / environnement IT</h3>\n            <div class=\"tl-org\">ENEO Cameroun</div>\n            <p class=\"tl-desc\">D\u00E9tails du stage \u00E0 compl\u00E9ter (missions, outils utilis\u00E9s).</p>\n          </div>\n        </div>\n        <div class=\"tl-item\">\n          <div class=\"tl-period\">Stage</div>\n          <div class=\"tl-content\">\n            <h3>Stage \u2014 support / environnement IT</h3>\n            <div class=\"tl-org\">SONATREL</div>\n            <p class=\"tl-desc\">D\u00E9tails du stage \u00E0 compl\u00E9ter (missions, outils utilis\u00E9s).</p>\n          </div>\n        </div>\n      </div>\n    </div>\n\n    <div class=\"seeking-box\">\n      <h3>Ce que je cherche</h3>\n      <ul>\n        <li>Une opportunit\u00E9 junior en d\u00E9veloppement Front-End / Angular</li>\n        <li>Une \u00E9quipe o\u00F9 le code est relu, discut\u00E9, am\u00E9lior\u00E9</li>\n        <li>Un environnement pour progresser rapidement et durablement</li>\n        <li>La possibilit\u00E9 d'apporter aussi une culture support / IT</li>\n      </ul>\n      <a routerLink=\"/contact\" class=\"btn btn-primary\" style=\"margin-top:20px; width:100%; justify-content:center;\">Me contacter</a>\n    </div>\n  </div>\n</section>\n", styles: [".about-grid { display: grid; grid-template-columns: 1.4fr 1fr; gap: 64px; }\n.about-grid h1 { font-size: clamp(1.9rem, 4vw, 2.5rem); margin-top: 10px; }\n.about-grid > div > p { color: var(--color-text-muted); margin: 16px 0; font-size: 1.02rem; }\n.about-grid strong { color: var(--color-text); font-weight: 500; }\n.about-grid h2 { font-size: 1.3rem; margin-top: 48px; margin-bottom: 24px; }\n\n.seeking-box {\n  background: var(--color-surface); border: 1px solid var(--color-border);\n  border-left: 2px solid var(--color-primary); border-radius: 4px;\n  padding: 26px 24px; align-self: start;\n}\n.seeking-box h3 { font-size: 1rem; margin-bottom: 14px; }\n.seeking-box ul li { font-size: 0.92rem; color: var(--color-text-muted); padding: 7px 0; border-top: 1px dashed var(--color-border); }\n.seeking-box ul li:first-child { border-top: none; }\n\n.timeline { position: relative; }\n.tl-item { display: grid; grid-template-columns: 130px 1fr; gap: 24px; padding: 22px 0; border-top: 1px solid var(--color-border); }\n.tl-item:first-child { border-top: none; padding-top: 0; }\n.tl-period { font-family: var(--font-mono); font-size: 0.76rem; color: var(--color-text-faint); padding-top: 3px; }\n.tl-content h3 { font-size: 1rem; font-family: var(--font-body); font-weight: 600; }\n.tl-org { font-family: var(--font-mono); font-size: 0.78rem; color: var(--color-secondary); margin-top: 3px; }\n.tl-desc { color: var(--color-text-muted); font-size: 0.9rem; margin-top: 8px; }\n\n@media (max-width: 900px) { .about-grid { grid-template-columns: 1fr; } }\n@media (max-width: 640px) { .tl-item { grid-template-columns: 1fr; gap: 6px; } }\n"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(About, { className: "About", filePath: "app/features/about/about.ts", lineNumber: 11 }); })();
//# sourceMappingURL=about.js.map