import { Component } from '@angular/core';
import * as i0 from "@angular/core";
export class ProfileCard {
    static ɵfac = function ProfileCard_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || ProfileCard)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: ProfileCard, selectors: [["app-profile-card"]], decls: 112, vars: 2, consts: [["role", "img", "aria-label", "Carte de profil d\u00E9veloppeur Angular", 1, "code-card"], [1, "float-badge", "badge-angular"], ["width", "15", "height", "15", "viewBox", "0 0 24 24", "fill", "none", "stroke", "currentColor", "stroke-width", "1.8", "stroke-linecap", "round", "stroke-linejoin", "round"], ["cx", "12", "cy", "12", "r", "9"], ["d", "M12 7l5 10M12 7l-5 10M9.5 13h5"], [1, "float-badge", "badge-typescript"], ["d", "M9 18l6-6-6-6"], ["d", "M15 12h-6"], [1, "float-badge", "badge-rxjs"], ["d", "M12 2v4M9 3.5l3 3 3-3M6 12a6 6 0 1 1 12 0 6 6 0 0 1-12 0z"], [1, "code-card-header"], [1, "code-dots"], [1, "code-dot", "red"], [1, "code-dot", "yellow"], [1, "code-dot", "green"], [1, "code-file"], [1, "code-status"], [1, "code-body"], [1, "code-comment"], [1, "code-keyword"], [1, "code-property"], [1, "code-punctuation"], [1, "code-string"], [1, "code-cursor"], [1, "code-card-footer"], [1, "code-lint"], [1, "code-lint", "success"]], template: function ProfileCard_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "div", 0)(1, "div", 1);
            i0.ɵɵnamespaceSVG();
            i0.ɵɵdomElementStart(2, "svg", 2);
            i0.ɵɵdomElement(3, "circle", 3)(4, "path", 4);
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(5, " Angular ");
            i0.ɵɵdomElementEnd();
            i0.ɵɵnamespaceHTML();
            i0.ɵɵdomElementStart(6, "div", 5);
            i0.ɵɵnamespaceSVG();
            i0.ɵɵdomElementStart(7, "svg", 2);
            i0.ɵɵdomElement(8, "path", 6)(9, "path", 7);
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(10, " TypeScript ");
            i0.ɵɵdomElementEnd();
            i0.ɵɵnamespaceHTML();
            i0.ɵɵdomElementStart(11, "div", 8);
            i0.ɵɵnamespaceSVG();
            i0.ɵɵdomElementStart(12, "svg", 2);
            i0.ɵɵdomElement(13, "path", 9);
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(14, " RxJS ");
            i0.ɵɵdomElementEnd();
            i0.ɵɵnamespaceHTML();
            i0.ɵɵdomElementStart(15, "div", 10)(16, "div", 11);
            i0.ɵɵdomElement(17, "span", 12)(18, "span", 13)(19, "span", 14);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(20, "span", 15);
            i0.ɵɵtext(21, "profile.ts");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(22, "span", 16);
            i0.ɵɵtext(23, "\u25CF OK");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(24, "div", 17)(25, "pre")(26, "code")(27, "span", 18);
            i0.ɵɵtext(28, "// Profil d\u00E9veloppeur \u2014 portfolio");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(29, "\n");
            i0.ɵɵdomElementStart(30, "span", 19);
            i0.ɵɵtext(31, "export");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(32, " ");
            i0.ɵɵdomElementStart(33, "span", 19);
            i0.ɵɵtext(34, "const");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(35, " ");
            i0.ɵɵdomElementStart(36, "span", 20);
            i0.ɵɵtext(37, "profile");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(38, " ");
            i0.ɵɵdomElementStart(39, "span", 21);
            i0.ɵɵtext(40);
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(41, "\n");
            i0.ɵɵdomElementStart(42, "span", 20);
            i0.ɵɵtext(43, "  name");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(44, "span", 21);
            i0.ɵɵtext(45, ":");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(46, " ");
            i0.ɵɵdomElementStart(47, "span", 22);
            i0.ɵɵtext(48, "'Fid\u00E8le Elock Sadrack'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(49, "span", 21);
            i0.ɵɵtext(50, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(51, "\n");
            i0.ɵɵdomElementStart(52, "span", 20);
            i0.ɵɵtext(53, "  role");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(54, "span", 21);
            i0.ɵɵtext(55, ":");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(56, " ");
            i0.ɵɵdomElementStart(57, "span", 22);
            i0.ɵɵtext(58, "'D\u00E9veloppeur Front-End Angular'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(59, "span", 21);
            i0.ɵɵtext(60, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(61, "\n");
            i0.ɵɵdomElementStart(62, "span", 20);
            i0.ɵɵtext(63, "  location");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(64, "span", 21);
            i0.ɵɵtext(65, ":");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(66, " ");
            i0.ɵɵdomElementStart(67, "span", 22);
            i0.ɵɵtext(68, "'Douala, Cameroun'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(69, "span", 21);
            i0.ɵɵtext(70, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(71, "\n");
            i0.ɵɵdomElementStart(72, "span", 20);
            i0.ɵɵtext(73, "  stack");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(74, "span", 21);
            i0.ɵɵtext(75, ":");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(76, " [");
            i0.ɵɵdomElementStart(77, "span", 22);
            i0.ɵɵtext(78, "'Angular'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(79, "span", 21);
            i0.ɵɵtext(80, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(81, " ");
            i0.ɵɵdomElementStart(82, "span", 22);
            i0.ɵɵtext(83, "'TypeScript'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(84, "span", 21);
            i0.ɵɵtext(85, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(86, " ");
            i0.ɵɵdomElementStart(87, "span", 22);
            i0.ɵɵtext(88, "'RxJS'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(89, "span", 21);
            i0.ɵɵtext(90, "]");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(91, "span", 21);
            i0.ɵɵtext(92, ",");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(93, "\n");
            i0.ɵɵdomElementStart(94, "span", 20);
            i0.ɵɵtext(95, "  experience");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(96, "span", 21);
            i0.ɵɵtext(97, ":");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(98, " ");
            i0.ɵɵdomElementStart(99, "span", 22);
            i0.ɵɵtext(100, "'Angular Talent Lab 2026 \u00B7 ODC'");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(101, "\n");
            i0.ɵɵdomElementStart(102, "span", 21);
            i0.ɵɵtext(103);
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(104, "\n");
            i0.ɵɵdomElementStart(105, "span", 23);
            i0.ɵɵtext(106, "|");
            i0.ɵɵdomElementEnd()()()();
            i0.ɵɵdomElementStart(107, "div", 24)(108, "span", 25);
            i0.ɵɵtext(109, "\u25CF No errors");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(110, "span", 26);
            i0.ɵɵtext(111, "\u25CF Compiled in 1.2s");
            i0.ɵɵdomElementEnd()()();
        } if (rf & 2) {
            i0.ɵɵadvance(40);
            i0.ɵɵtextInterpolate1("= ", "{");
            i0.ɵɵadvance(63);
            i0.ɵɵtextInterpolate1("", "}", ";");
        } }, styles: ["\r\n[_nghost-%COMP%] {\r\n  display: block;\r\n}\r\n\r\n.code-card[_ngcontent-%COMP%] {\r\n  background: rgba(21, 28, 38, 0.85);\r\n  border: 1px solid rgba(240, 169, 62, 0.15);\r\n  border-radius: 16px;\r\n  overflow: hidden;\r\n  box-shadow:\r\n    0 30px 80px -20px rgba(0, 0, 0, 0.7),\r\n    0 0 60px -20px rgba(240, 169, 62, 0.15),\r\n    inset 0 1px 0 rgba(255, 255, 255, 0.04);\r\n  backdrop-filter: blur(20px);\r\n  transform-style: preserve-3d;\r\n  position: relative;\r\n  width: 100%;\r\n  max-width: 420px;\r\n}\r\n\r\n.code-card[_ngcontent-%COMP%]::before {\r\n  content: '';\r\n  position: absolute;\r\n  top: 0;\r\n  left: -60%;\r\n  width: 50%;\r\n  height: 100%;\r\n  background: linear-gradient(105deg, transparent, rgba(255, 255, 255, 0.03), transparent);\r\n  animation: _ngcontent-%COMP%_shimmer-sweep 4s ease-in-out infinite;\r\n  pointer-events: none;\r\n}\r\n\r\n@keyframes _ngcontent-%COMP%_shimmer-sweep {\r\n  0% { left: -60%; }\r\n  50%, 100% { left: 120%; }\r\n}\r\n\r\n.code-card-header[_ngcontent-%COMP%] {\r\n  display: flex;\r\n  align-items: center;\r\n  gap: 12px;\r\n  padding: 14px 18px;\r\n  background: rgba(15, 20, 28, 0.9);\r\n  border-bottom: 1px solid var(--%NS%color-border);\r\n}\r\n\r\n.code-dots[_ngcontent-%COMP%] { display: flex; gap: 6px; }\r\n.code-dot[_ngcontent-%COMP%] {\r\n  width: 10px;\r\n  height: 10px;\r\n  border-radius: 50%;\r\n}\r\n.code-dot.red[_ngcontent-%COMP%] { background: #FF5F57; }\r\n.code-dot.yellow[_ngcontent-%COMP%] { background: #FEBC2E; }\r\n.code-dot.green[_ngcontent-%COMP%] { background: #28C840; }\r\n\r\n.code-file[_ngcontent-%COMP%] {\r\n  flex: 1;\r\n  font-family: var(--%NS%font-mono);\r\n  font-size: 0.75rem;\r\n  color: var(--%NS%color-text-muted);\r\n  text-align: center;\r\n}\r\n\r\n.code-status[_ngcontent-%COMP%] {\r\n  font-family: var(--%NS%font-mono);\r\n  font-size: 0.65rem;\r\n  color: var(--%NS%color-secondary);\r\n  background: rgba(78, 201, 160, 0.1);\r\n  padding: 3px 10px;\r\n  border-radius: 100px;\r\n}\r\n\r\n.code-body[_ngcontent-%COMP%] {\r\n  padding: 26px 20px 20px;\r\n  overflow-x: auto;\r\n}\r\n\r\n.code-body[_ngcontent-%COMP%]   pre[_ngcontent-%COMP%] {\r\n  font-family: var(--%NS%font-mono);\r\n  font-size: 0.8rem;\r\n  line-height: 1.9;\r\n  color: var(--%NS%color-text-muted);\r\n  white-space: pre;\r\n  margin: 0;\r\n}\r\n\r\n.code-comment[_ngcontent-%COMP%] { color: var(--%NS%color-text-faint); font-style: italic; }\r\n.code-keyword[_ngcontent-%COMP%] { color: #C792EA; }\r\n.code-string[_ngcontent-%COMP%] { color: var(--%NS%color-primary); }\r\n.code-property[_ngcontent-%COMP%] { color: var(--%NS%color-accent); }\r\n.code-punctuation[_ngcontent-%COMP%] { color: var(--%NS%color-text-faint); }\r\n\r\n.code-cursor[_ngcontent-%COMP%] {\r\n  display: inline-block;\r\n  color: var(--%NS%color-primary);\r\n  animation: _ngcontent-%COMP%_blink-cursor 1s steps(1) infinite;\r\n  margin-left: 2px;\r\n}\r\n\r\n@keyframes _ngcontent-%COMP%_blink-cursor {\r\n  50% { opacity: 0; }\r\n}\r\n\r\n.code-card-footer[_ngcontent-%COMP%] {\r\n  display: flex;\r\n  gap: 16px;\r\n  padding: 12px 18px;\r\n  border-top: 1px solid var(--%NS%color-border);\r\n  background: rgba(15, 20, 28, 0.6);\r\n}\r\n\r\n.code-lint[_ngcontent-%COMP%] {\r\n  font-family: var(--%NS%font-mono);\r\n  font-size: 0.65rem;\r\n  color: var(--%NS%color-text-faint);\r\n}\r\n.code-lint.success[_ngcontent-%COMP%] {\r\n  color: var(--%NS%color-secondary);\r\n  margin-left: auto;\r\n}\r\n\r\n\r\n.float-badge[_ngcontent-%COMP%] {\r\n  position: absolute;\r\n  display: flex;\r\n  align-items: center;\r\n  gap: 6px;\r\n  font-family: var(--%NS%font-mono);\r\n  font-size: 0.7rem;\r\n  color: var(--%NS%color-text);\r\n  background: rgba(21, 28, 38, 0.9);\r\n  border: 1px solid var(--%NS%color-border);\r\n  border-radius: 100px;\r\n  padding: 8px 14px;\r\n  backdrop-filter: blur(12px);\r\n  box-shadow: 0 8px 32px -8px rgba(0, 0, 0, 0.5);\r\n  animation: _ngcontent-%COMP%_float-badge 5s ease-in-out infinite;\r\n  z-index: 3;\r\n}\r\n\r\n.badge-angular[_ngcontent-%COMP%] { top: 8%; left: -30px; animation-delay: 0s; }\r\n.badge-typescript[_ngcontent-%COMP%] { bottom: 18%; right: -25px; animation-delay: -1.5s; }\r\n.badge-rxjs[_ngcontent-%COMP%] { bottom: -15px; left: 18%; animation-delay: -3s; }\r\n\r\n@keyframes _ngcontent-%COMP%_float-badge {\r\n  0%, 100% { transform: translateY(0); }\r\n  50% { transform: translateY(-10px); }\r\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(ProfileCard, [{
        type: Component,
        args: [{ selector: 'app-profile-card', standalone: true, template: "<div class=\"code-card\" role=\"img\" aria-label=\"Carte de profil d\u00E9veloppeur Angular\">\r\n  <div class=\"float-badge badge-angular\">\r\n    <svg width=\"15\" height=\"15\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n      <circle cx=\"12\" cy=\"12\" r=\"9\"/>\r\n      <path d=\"M12 7l5 10M12 7l-5 10M9.5 13h5\"/>\r\n    </svg>\r\n    Angular\r\n  </div>\r\n  <div class=\"float-badge badge-typescript\">\r\n    <svg width=\"15\" height=\"15\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n      <path d=\"M9 18l6-6-6-6\"/>\r\n      <path d=\"M15 12h-6\"/>\r\n    </svg>\r\n    TypeScript\r\n  </div>\r\n  <div class=\"float-badge badge-rxjs\">\r\n    <svg width=\"15\" height=\"15\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n      <path d=\"M12 2v4M9 3.5l3 3 3-3M6 12a6 6 0 1 1 12 0 6 6 0 0 1-12 0z\"/>\r\n    </svg>\r\n    RxJS\r\n  </div>\r\n\r\n  <div class=\"code-card-header\">\r\n    <div class=\"code-dots\">\r\n      <span class=\"code-dot red\"></span>\r\n      <span class=\"code-dot yellow\"></span>\r\n      <span class=\"code-dot green\"></span>\r\n    </div>\r\n    <span class=\"code-file\">profile.ts</span>\r\n    <span class=\"code-status\">\u25CF OK</span>\r\n  </div>\r\n\r\n  <div class=\"code-body\">\r\n<pre><code><span class=\"code-comment\">// Profil d\u00E9veloppeur \u2014 portfolio</span>\r\n<span class=\"code-keyword\">export</span> <span class=\"code-keyword\">const</span> <span class=\"code-property\">profile</span> <span class=\"code-punctuation\">= {{ '{' }}</span>\r\n<span class=\"code-property\">  name</span><span class=\"code-punctuation\">:</span> <span class=\"code-string\">'Fid\u00E8le Elock Sadrack'</span><span class=\"code-punctuation\">,</span>\r\n<span class=\"code-property\">  role</span><span class=\"code-punctuation\">:</span> <span class=\"code-string\">'D\u00E9veloppeur Front-End Angular'</span><span class=\"code-punctuation\">,</span>\r\n<span class=\"code-property\">  location</span><span class=\"code-punctuation\">:</span> <span class=\"code-string\">'Douala, Cameroun'</span><span class=\"code-punctuation\">,</span>\r\n<span class=\"code-property\">  stack</span><span class=\"code-punctuation\">:</span> [<span class=\"code-string\">'Angular'</span><span class=\"code-punctuation\">,</span> <span class=\"code-string\">'TypeScript'</span><span class=\"code-punctuation\">,</span> <span class=\"code-string\">'RxJS'</span><span class=\"code-punctuation\">]</span><span class=\"code-punctuation\">,</span>\r\n<span class=\"code-property\">  experience</span><span class=\"code-punctuation\">:</span> <span class=\"code-string\">'Angular Talent Lab 2026 \u00B7 ODC'</span>\r\n<span class=\"code-punctuation\">{{ '}' }};</span>\r\n<span class=\"code-cursor\">|</span></code></pre>\r\n  </div>\r\n\r\n  <div class=\"code-card-footer\">\r\n    <span class=\"code-lint\">\u25CF No errors</span>\r\n    <span class=\"code-lint success\">\u25CF Compiled in 1.2s</span>\r\n  </div>\r\n</div>\r\n", styles: ["/* ============ PROFILE CODE CARD ============ */\r\n:host {\r\n  display: block;\r\n}\r\n\r\n.code-card {\r\n  background: rgba(21, 28, 38, 0.85);\r\n  border: 1px solid rgba(240, 169, 62, 0.15);\r\n  border-radius: 16px;\r\n  overflow: hidden;\r\n  box-shadow:\r\n    0 30px 80px -20px rgba(0, 0, 0, 0.7),\r\n    0 0 60px -20px rgba(240, 169, 62, 0.15),\r\n    inset 0 1px 0 rgba(255, 255, 255, 0.04);\r\n  backdrop-filter: blur(20px);\r\n  transform-style: preserve-3d;\r\n  position: relative;\r\n  width: 100%;\r\n  max-width: 420px;\r\n}\r\n\r\n.code-card::before {\r\n  content: '';\r\n  position: absolute;\r\n  top: 0;\r\n  left: -60%;\r\n  width: 50%;\r\n  height: 100%;\r\n  background: linear-gradient(105deg, transparent, rgba(255, 255, 255, 0.03), transparent);\r\n  animation: shimmer-sweep 4s ease-in-out infinite;\r\n  pointer-events: none;\r\n}\r\n\r\n@keyframes shimmer-sweep {\r\n  0% { left: -60%; }\r\n  50%, 100% { left: 120%; }\r\n}\r\n\r\n.code-card-header {\r\n  display: flex;\r\n  align-items: center;\r\n  gap: 12px;\r\n  padding: 14px 18px;\r\n  background: rgba(15, 20, 28, 0.9);\r\n  border-bottom: 1px solid var(--color-border);\r\n}\r\n\r\n.code-dots { display: flex; gap: 6px; }\r\n.code-dot {\r\n  width: 10px;\r\n  height: 10px;\r\n  border-radius: 50%;\r\n}\r\n.code-dot.red { background: #FF5F57; }\r\n.code-dot.yellow { background: #FEBC2E; }\r\n.code-dot.green { background: #28C840; }\r\n\r\n.code-file {\r\n  flex: 1;\r\n  font-family: var(--font-mono);\r\n  font-size: 0.75rem;\r\n  color: var(--color-text-muted);\r\n  text-align: center;\r\n}\r\n\r\n.code-status {\r\n  font-family: var(--font-mono);\r\n  font-size: 0.65rem;\r\n  color: var(--color-secondary);\r\n  background: rgba(78, 201, 160, 0.1);\r\n  padding: 3px 10px;\r\n  border-radius: 100px;\r\n}\r\n\r\n.code-body {\r\n  padding: 26px 20px 20px;\r\n  overflow-x: auto;\r\n}\r\n\r\n.code-body pre {\r\n  font-family: var(--font-mono);\r\n  font-size: 0.8rem;\r\n  line-height: 1.9;\r\n  color: var(--color-text-muted);\r\n  white-space: pre;\r\n  margin: 0;\r\n}\r\n\r\n.code-comment { color: var(--color-text-faint); font-style: italic; }\r\n.code-keyword { color: #C792EA; }\r\n.code-string { color: var(--color-primary); }\r\n.code-property { color: var(--color-accent); }\r\n.code-punctuation { color: var(--color-text-faint); }\r\n\r\n.code-cursor {\r\n  display: inline-block;\r\n  color: var(--color-primary);\r\n  animation: blink-cursor 1s steps(1) infinite;\r\n  margin-left: 2px;\r\n}\r\n\r\n@keyframes blink-cursor {\r\n  50% { opacity: 0; }\r\n}\r\n\r\n.code-card-footer {\r\n  display: flex;\r\n  gap: 16px;\r\n  padding: 12px 18px;\r\n  border-top: 1px solid var(--color-border);\r\n  background: rgba(15, 20, 28, 0.6);\r\n}\r\n\r\n.code-lint {\r\n  font-family: var(--font-mono);\r\n  font-size: 0.65rem;\r\n  color: var(--color-text-faint);\r\n}\r\n.code-lint.success {\r\n  color: var(--color-secondary);\r\n  margin-left: auto;\r\n}\r\n\r\n/* ============ FLOATING BADGES ============ */\r\n.float-badge {\r\n  position: absolute;\r\n  display: flex;\r\n  align-items: center;\r\n  gap: 6px;\r\n  font-family: var(--font-mono);\r\n  font-size: 0.7rem;\r\n  color: var(--color-text);\r\n  background: rgba(21, 28, 38, 0.9);\r\n  border: 1px solid var(--color-border);\r\n  border-radius: 100px;\r\n  padding: 8px 14px;\r\n  backdrop-filter: blur(12px);\r\n  box-shadow: 0 8px 32px -8px rgba(0, 0, 0, 0.5);\r\n  animation: float-badge 5s ease-in-out infinite;\r\n  z-index: 3;\r\n}\r\n\r\n.badge-angular { top: 8%; left: -30px; animation-delay: 0s; }\r\n.badge-typescript { bottom: 18%; right: -25px; animation-delay: -1.5s; }\r\n.badge-rxjs { bottom: -15px; left: 18%; animation-delay: -3s; }\r\n\r\n@keyframes float-badge {\r\n  0%, 100% { transform: translateY(0); }\r\n  50% { transform: translateY(-10px); }\r\n}\r\n"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(ProfileCard, { className: "ProfileCard", filePath: "app/features/home/components/profile-card/profile-card.ts", lineNumber: 9 }); })();
//# sourceMappingURL=profile-card.js.map